language: ruby
rvm:
  - 2.4.1
env:
  - DB=pgsql

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - psql -c 'create database sales_app_test;' -U postgres
  - bundle exec rake db:migrate

test:
  adapter: postgresql
  database: sales_app_test
  username: postgres

