language: ruby
rvm:
  - 2.4.1
  

services:
  - postgresql

postgres:
  adapter: postgresql
  database: sales_app_test
  username: postgres

before_script:
  - "psql -c 'create database sales_app_test;' -U postgres"
  - "rake db:migrate"  